### ISSUE TITLE
Update solution to plugin-sdk

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO4#11]
As a continuation of #7 we need to replace GTASA dependency in a solution file so the project is buildable.

Might want to include plugin-sdk as a git submodule.
@thelink2012 what do you think?

**Comment by thelink2012** [comment]
That was the plan, will work on merging that ASAP.

**Comment by x87** [comment]
@thelink2012 need to implement git submodule, right?

**Comment by thelink2012** [comment]
Done
