### ISSUE TITLE
Update project to the latest Visual Studio?

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO4#12]
Currently it's bound to VS2010.

What are the pros/cons of having the project updated to VS2015 or VS2017?

**Comment by Deji69** [comment]
No pros really, the source barely uses any modern C++ features so I wouldn't say there's much point in upgrading. Plus 2010 was a pretty popular version and I think XP compatible so more people will probably still use it.

If much work needed to go into it I'd say add CMake to allow generation of any project version.

**Comment by thelink2012** [comment]
I agree on CMake over the solution files.

VS2015/2017 runtime works on XP SP3 with the *_xp* toolset if the thread-safe init flag is disabled, so it shouldn't be a big deal.

**Comment by ThirteenAG** [comment]
Why not premake5 though?

**Comment by x87** [comment]
related to #4

**Comment by thelink2012** [comment]
See 2b98d1ad3c83, have removed the solutions file and switched to a CMake script. To build for XP, either going manually into the options and setting the `vs1XX_xp` toolset, or using the CMake option `-T vs1XX_xp` is required.

CMake doesn't directly support pre-compiled headers, but I doubt CLEO has such a big build time.

Also, we're building only a small subset of plugin-sdk :)

**Comment by x87** [comment]
@thelink2012 could you please also provide a step-by-step guide on installing and building the library within new workflow?

**Comment by thelink2012** [comment]
@x87 done.

**Comment by x87** [comment]
Thank you! Closed.
