### ISSUE TITLE
GET_SCRIPT_STRUCT_NAMED does not work with scripts created with "start_new_script"

### ISSUE THREAD

**Issue by Joaom-eng** [cleolibrary/CLEO4#149]
I'm trying to modify a script from main.scm that is created with start_new_script, but when I try to get its pointer using GET_SCRIPT_STRUCT_NAMED, it doesn't return anything. I'm referring to the "R3" script that handles vehicle sub-missions (vigilante, ambulance, etc.).
![image](https://github.com/user-attachments/assets/daf79f75-524e-4ae4-a407-5db5bc257e71)
![image2](https://github.com/user-attachments/assets/df29aeb9-17b5-4aef-a6cb-0ecb0c0f54eb)

This doesn't return true:
```scala
SCRIPT_START
{
    NOP
    LVAR_INT i

    SCRIPT_NAME PINTO
    WHILE TRUE
        WAIT 0
        GET_SCRIPT_STRUCT_NAMED R3 (i)
        IF i > 0x0
            PRINT_FORMATTED_NOW "O SCRIPT EXISTEEEEE" 2000
        ENDIF
    ENDWHILE
}
SCRIPT_END
```

**Comment by MiranDMC** [comment]
R3 is not valid string, and deducing from posted code it is not variable either. For calling **script_name** you used apostrophes.
![image](https://github.com/user-attachments/assets/eeaeae3a-c66d-45ef-a7fb-a43c62d115ee)
I guess GTA Script compiler ignores missing argument or puts 0 instead of it.

You can use CLEO5 which will probably complain will about invalid argument.

**Comment by KillerSAA** [comment]
> ```scala
> GET_SCRIPT_STRUCT_NAMED 
> ```

no bro... this is gta3script code, the compiler doesn't need '' or "" to be used, I've used GET_SCRIPT_STRUCT_NAMED before and it works normally, but it has this problem

**Comment by Joaom-eng** [comment]
> R3 is not valid string, and deducing from posted code it is not variable either. For calling script_name you used apostrophes. I guess GTA Script compiler ignores missing argument or puts 0 instead of it. ![imagem](https://private-user-images.githubusercontent.com/11084446/399094508-eeaeae3a-c66d-45ef-a7fb-a43c62d115ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NDA4NzAsIm5iZiI6MTczNTQ0MDU3MCwicGF0aCI6Ii8xMTA4NDQ0Ni8zOTkwOTQ1MDgtZWVhZWFlM2EtYzY2ZC00NWVmLWE3ZmItYTQzYzYyZDExNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDAyNDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDk3OWEwZTNjMWQwYjAxYWJiZGZlOWFiNWZlN2VmYWRhOGRlNGExMmY0ZTdjODVkMzRmYmVhMDNjZjc3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JNUATtPP6RxDJCjJuqp_TpbXixe_-VipvVH4t3A3qYQ)
> 
> You can use CLEO5 which will probably complain will about invalid argument.

no bro... this is gta3script code, the compiler doesn't need '' or "" to be used, I've used GET_SCRIPT_STRUCT_NAMED before and it works normally, but it has this problem

**Comment by MiranDMC** [comment]
This works as expected in 4.4.4:
```
{$CLEO .cs}

script_name {name} "search"
while true
    wait {time} 0
    
    print_string_now {text} "Looking for the script..." {time} 1

    int ptr = get_script_struct_named {scriptName} "R3"
    if
        ptr <> 0
    then
        print_formatted_now {format} "Script found at %p" {time} 1 {args} ptr
    end
end

terminate_this_custom_script
```

```
{$CLEO .cs}

script_name {name} 'R3'

while true
    wait 0
    
    if
        test_cheat {input} "1"
    then
        shortString newName
        
        int num = generate_random_int
        num %= 4
        
        int rnd = generate_random_int
        if
            is_local_var_bit_set_const {var_number} rnd {bitIndex} 0
        then
            string_format newName = "R%d" num
        else
            string_format newName = "r%d" num
        end
        
        print_help_formatted {text} "New script name~n~%s" {args} newName
        script_name {name} newName
    end
end

terminate_this_custom_script
```

It also detects some script when game with standard main.scm is running.
![image](https://github.com/user-attachments/assets/aec9abad-eeb1-4a66-95a4-0bde6242cc3d)

**Comment by JuniorDjjr** [comment]
The title says the issue is with `start_new_script`, not .cs files.
I also had this issue too, but I don't remember if was CLEO 4.4.4 or older.

**Comment by Joaom-eng** [comment]
sorry, actually my version is out of date, this works perfectly
