### ISSUE TITLE
Audio streams continue playing after the game window loses focus (possible solution provided)

### ISSUE THREAD

**Issue by dkluin** [cleolibrary/CLEO4#23]
This is a bug which exists for quite a long time now. It happens because the WM_ACTIVATE event in the DefWindowProc() hook is not handled properly. WM_ACTIVATE fires whenever a window **gains or  loses** focus, and thus one would need to check the WPARAMS argument and call PauseStreams() and ResumeStreams() accordingly.

Source:
https://github.com/cleolibrary/CLEO4/blob/e36ec856f55466789cc82ae62acf914a693db06a/source/CSoundSystem.cpp#L37

**Comment by JuniorDjjr** [comment]
Fixed #25
