### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by leonardoInf** [cleolibrary/CLEO4#24]
I am using VS 2019 and I have installed plugin-sdk but the compiler keeps complaining about CRGBA and PluginBase.h.
Can you reintroduce the CMakefile? Is there an older version of plugin-sdk I need to use?

**Comment by leonardoInf** [comment]
I have found a solution. I use VS 2017 now but I guess that this does not matter.

1. Download my downgraded and slightly fork of plugin-sdk: https://github.com/leonardoInf/plugin-sdk and install it like any other version of plugin-sdk.
2. Download my updated fork of CLEO4: https://github.com/leonardoInf/CLEO4
3. Open CLEO4.sln in VS. You might have to do the following:
   - Select Release
   - Change Windows SDK version if neccesarry
   - Change platform toolset if neccesary
4. Just build the solution. If there are strange compiler errors, try rebuilding.

**Comment by x87** [comment]
@leonardoInf those issues with plugin-sdk should be resolved now. In order to compile the code one should have the latest version of the plugin-sdk code and have the environment variable  `PLUGIN_SDK_DIR` set to the directory with that code.
