### ISSUE TITLE
Investigate a crash on v.4.4.0

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO4#28]
`0AEA GET_PED_REF` is crashing. 4.3.24 is fine.
`Unhandled exception at 0x71037882 in CLEO.asi (+0x7882): 0xC0000005: Access violation reading location 0xF7F50BC5.`
I can try to debug and fix it but I need to update by VS and build tools before it.

_Originally posted by @JuniorDjjr in https://github.com/cleolibrary/CLEO4/pull/26#issuecomment-714833473_

**Comment by JuniorDjjr** [comment]
Oh, this is interesting: it's not a bug, but a feature. Old CLEO version didn't crash, **but this is a script error**, so, the crash is necessary. I fixed it and it's working.

I think everything is ok, tested on 140+ CLEO scripts installation.

**Comment by thelink2012** [comment]
What's the problem with the script?

**Comment by JuniorDjjr** [comment]
There was a sum of 0x36 in the pointer sent to GET_PED_REF (used before to check entity type). It impresses me it doesn't cause a crash on previous version or with optimization disabled. The mod has been published for 1 year and no one has reported that crash.

**Comment by x87** [comment]
Good to know, thanks

**Comment by x87** [comment]
I have included updated plugins into 4.4.0 archive
https://github.com/cleolibrary/CLEO4/releases/tag/v4.4.0
