### ISSUE TITLE
Duplicate entities on running the script multiple times

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO4#3]
If a script creates a new entity in game (a parking lot, a marker, whatever to be stored in the savegame), and the player saves, then loads the save, the entity is recreated again, as the script is running. The only thing to avoid that is to use [enable_thread_saving](https://github.com/cleolibrary/CLEO4/blob/master/CCustomOpcodeSystem.cpp#L1006) opcode. But if it's missed the mess happens. Need to find the way to not duplicate entities again and again.

**Comment by thelink2012** [comment]
See #6 also

**Comment by x87** [comment]
See #6
