### ISSUE TITLE
CLEO 4.4.0 crash (probably because of .ini opcodes)

### ISSUE THREAD

**Issue by VitalRus95** [cleolibrary/CLEO4#31]
The newest CLEO version, **4.4.0**, may cause GTA SA crashes. In my case it happened when I tried to launch one of my MPACKs. The last opcode captured by SCRLog is `[0AF0] READ_INT_FROM_INI_FILE`. Deleting the .ini and trying to create a new one from the code leads to the last command being `[0AF1] WRITE_INT_TO_INI_FILE 0`. Reinstalling an older version (**4.3.22**) of CLEO solves the problem. The logs are the following:

- CLEO log: [cleo.log](https://github.com/cleolibrary/CLEO4/files/5440184/cleo.log)
- SCRLog, reading an existing .ini: [scrlog.log](https://github.com/cleolibrary/CLEO4/files/5440185/scrlog.log)
- SCRLog, attempt to create a new .ini: [scrlog.log](https://github.com/cleolibrary/CLEO4/files/5440205/scrlog.log)

Thank you for attention and any help!

**Comment by x87** [comment]
@VitalRus95 hi Vital! It might be caused by [this change](https://github.com/cleolibrary/CLEO4/commit/b7ef2f48e9ba676366c309fbbb08d24f7eb13fd2) 

Can you please share the script that fails?

**Comment by VitalRus95** [comment]
@x87, thanks for reply! Yes, of course. Here's an extract of the code where the two mentioned crashes occur. They are lines 148 and 327 respectively: [.ini crash.txt](https://github.com/cleolibrary/CLEO4/files/5440311/default.ini.crash.txt). Hope that helps to find out what's wrong.

**Comment by x87** [comment]
@VitalRus95 I suspect that `scrlog` is what actually crashing. Can you try to remove the `scrlog` and run the script again?

**Comment by x87** [comment]
I'm not very familiar with SCRLog implementation but if I run the script:

```
{$CLEO .cs}
0000:
0AF1: write_int_to_ini_file 16 path "cleo\config.ini" section "SectionName" key "intKey"
0A93: end_custom_thread
```

SCRLog raises an exception
![0af1_bug](https://user-images.githubusercontent.com/5698288/97243816-86121a80-17cd-11eb-920f-4afba0bef588.png)

code inspection shows it fails in this line:

```
// making sure it is null terminated without any peformance effort...
if(str[max-1] == 0)
```

removing SCRLog allows the script to run without any visible issues.

@thelink2012 FYI ☝️

**Comment by thelink2012** [comment]
cc @JuniorDjjr since he's maintaining a up-to-date fork.

**Comment by x87** [comment]
Oh, I was not aware of the updated version. Looks like the script is working fine here.

@VitalRus95 can you try the SCRLog from here: https://www.mixmods.com.br/2020/09/scrlog.html
This page is not very user-friendly (rapidshare-like multi-step download in 2020? cmon...) but I don't know whether there is any mirror. Having a GitHub releases page would be quite pleasant.

**Comment by JuniorDjjr** [comment]
Update it on cleo.li, it also includes CLEO+ commands.
btw some commands are renamed to match gta3script, so they are now different from Sanny Builder SCR. I think less than 10.

**Comment by VitalRus95** [comment]
Thank you all for helpful suggestions! Both deleting the old SCRLog or updating it to @JuniorDjjr 's version (I downloaded the one from GitHub) solve the problem!
@x87, I think the new SCRLog deserves to become a part of tools that are distributed together with Sanny Builder. :-)
