### ISSUE TITLE
When I download its a WinRar Zip file

### ISSUE THREAD

**Issue by KaiDotExe** [cleolibrary/CLEO4#32]
Every time I download its a WinRar Zip file with no exe files or setups????????????????????

**Comment by KaiDotExe** [comment]
Anyone know how to install with Zip file?

**Comment by x87** [comment]
Unzip to the gta sa directory

**Comment by Celaro** [comment]
Simply download the WinRAR latest version from https://www.win-rar.com/predownload.html?&L=0 and install it. Then it will extract archived programs ready for you to install.
