### ISSUE TITLE
Virus File

### ISSUE THREAD

**Issue by JuuzouSuzuya2** [cleolibrary/CLEO4#33]
When i had windows 7, i wanted to mod gta san so i installed Cleo, went to cleo.li but then i got viruses everywhere and my Appdata folders are also infected by the virus.

**Comment by x87** [comment]
Got any report? Which files are infected and what kind of virus?

**Comment by JuuzouSuzuya2** [comment]
The files are random named, Like fidisn75 and inside it they mostly have
emoji that has heart icon, And they are constantly reproducing itself in
task Manager too, i had hard time remocing them so had to reinstall win7

9 Kas 2020 Pzt 16:50 tarihinde x87 <notifications@github.com> şunu yazdı:

**Comment by x87** [comment]
How do you know it is from cleo.li?

**Comment by JuuzouSuzuya2** [comment]
1:The files are secure i scanned them too, but in virustotal Cleo was scanned as safe (Although other files was fine.), Then runned it for first day of modding gta san, Then after one day, something bad happened, they were all NSFW files, and i know it's cleo li because other files was only, GTA TURK vice city, Photos, Videos of my channel, texts, Documents, and only cleo was cause to infect my pc.

**Comment by x87** [comment]
Please provide a link to a file or script hosted on cleo.li that is reported as a virus.

**Comment by JuuzouSuzuya2** [comment]
https://cleo.li/

**Comment by x87** [comment]
I'm closing this until I get this

>a link to a file or script hosted on cleo.li that is reported as a virus.

**Comment by JuuzouSuzuya2** [comment]
Alr.
