### ISSUE TITLE
CLEO 4.4 Crashes on GTASA 1.01

### ISSUE THREAD

**Issue by xWendz** [cleolibrary/CLEO4#35]
after installing cleo 4.4 on gta sa folder my gta keeps on crashing what should I do?

here's the cleo.log file from gta sa directory

03/01/2021 18:51:59.755 Log started.
03/01/2021 18:51:59.755 Unprotecting memory region '.text': 0x00001000 (size: 0x00457000)
03/01/2021 18:51:59.755 Unprotecting memory region '.rdata': 0x00459000 (size: 0x0004C000)
03/01/2021 18:51:59.755 Unprotecting memory region '.text': 0x008B3000 (size: 0x00528000)
03/01/2021 18:51:59.755 Unloading plugins...
03/01/2021 18:51:59.755 Loading plugin cleo/FileSystemOperations.cleo
03/01/2021 18:51:59.802 Loading plugin cleo/IniFiles.cleo
03/01/2021 18:51:59.802 Loading plugin cleo/IntOperations.cleo
03/01/2021 18:51:59.833 Started on game of version: SA 1.01 eu
03/01/2021 18:51:59.833 Injecting MenuStatusNotifier...
03/01/2021 18:51:59.833 Replacing call: 0x0057BF71
03/01/2021 18:51:59.833 Injecting DmaFix...
03/01/2021 18:51:59.833 Replacing call: 0x0053EE21
03/01/2021 18:51:59.833 Injecting TextManager...
03/01/2021 18:51:59.833 Injecting function at: 0x006A0870
03/01/2021 18:51:59.833 Injecting SoundSystem...
03/01/2021 18:51:59.833 Replacing call: 0x0074907C
03/01/2021 18:51:59.833 Injecting CustomOpcodeSystem...
03/01/2021 18:51:59.833 Injecting ScriptEngine...
03/01/2021 18:51:59.833 Replacing call: 0x0046AE9B
03/01/2021 18:51:59.833 Replacing call: 0x0058DD22
03/01/2021 18:51:59.833 Replacing call: 0x005904B4
03/01/2021 18:51:59.833 Replacing call: 0x005D57B7
03/01/2021 18:51:59.833 Injecting function at: 0x005DEEA0
03/01/2021 18:51:59.833 Replacing call: 0x005D20D0
03/01/2021 18:51:59.833 Replacing call: 0x005D157C
03/01/2021 18:51:59.833 Injecting function at: 0x0046685B
03/01/2021 18:52:00.317 Creating main window...
03/01/2021 18:52:00.317 Found sound device 0: No sound
03/01/2021 18:52:00.317 Found sound device 1 (default): Speakers (Realtek High Definition Audio)
03/01/2021 18:52:00.317 Found sound device 2: Realtek Digital Output (Realtek High Definition Audio)
03/01/2021 18:52:00.317 Found sound device 3: LCD (NVIDIA High Definition Audio)
03/01/2021 18:52:00.317 On system found 4 devices, 4 enabled devices, assuming device to use: 1 (Speakers (Realtek High Definition Audio))
03/01/2021 18:52:00.349 SoundSystem initialized
03/01/2021 18:52:00.352 Floating-point audio supported!
03/01/2021 18:52:00.353 Audio hardware acceleration disabled (no EAX)
03/01/2021 18:52:40.201 Closing SoundSystem...
03/01/2021 18:52:40.201 Freeing BASS library
03/01/2021 18:52:40.202 SoundSystem closed!
03/01/2021 18:52:40.202 Deleting fxts...
03/01/2021 18:52:40.202 Unloading scripts...
03/01/2021 18:52:40.202 Log finished.

**Comment by xWendz** [comment]
I also tried this after posting this issue

-I added gta_sa.exe on DEP list on system properties
-executed the file in WinXP SP3 compatibility
-run as admin

**Comment by x87** [comment]
@xWendz Thanks for reporting. I actually tried to run gta sa with 1.01 exe (15,806,464 bytes) and CLEO 4.4 on-board and it crashed mid-loading with the same log output. I will have to investigate what went wrong but I must say that v1.01 is not very common for modding purposes. I would recommend to get v1.0 US version (gta_sa_compact.exe should suffice) and apply community patches on it. It's much more resilient to various modding libraries such as CLEO.

**Comment by xWendz** [comment]
thanks for the update, I will try to downgrade my game to 1.0

**Comment by xWendz** [comment]
update, I just did downgrade on v1.0 but didn't know where to get those community patches you were talking, Maybe can you give me a link or keyword of it. Thank you!

**Comment by x87** [comment]
Here is the link: https://gtamods.com/wiki/Game_Patches#Unofficial_Game_Patches
Probably the most known is SilentPatch.

**Comment by DrHesperus** [comment]
Hi, will Cleo be 5?

**Comment by danypacf** [comment]
> thanks for the update, I will try to downgrade my game to 1.0

I had this error too. I downloaded this file and worked like a charm. 

https://www.gtaall.net/gta-san-andreas/programs/135576-gta-sa-exe-1-0-us-original-version.html 

Download it without installer (ZIP).

It supports Cleo V4.4.0
