### ISSUE TITLE
GTA: SA v1.0.0.22 crashes with CLEO4.4

### ISSUE THREAD

**Issue by hesoyamhh** [cleolibrary/CLEO4#41]
I Installed GTA:SA from Repack having version 1.0.0.22 `GTA SA RiP by Christsnatcher`

The game runs fine without any mods. Also, Silent’s ASI Loader and SilentPatch runs fine with the game. So, the dll files seem to be compatible with game version.

But CLOE ceases to work with it.

These are the things which I did and my findings:

- Uninstall/Remove Silent files and then installed CLEO4.4
- When CLEO4.4 is installed (without any mods/scripts), the exe opens fine but the game crashes after loading screen  ends of New Game/Load Game. NOTE: No logs are generated i.e. cleo.log file is not generated.
- The point here is, the game crashes even if I go to Audio Settings and change the radio stations. So, I suspected it might be due to bass.dll file
- So, I tried to use latest bass.dll v2.4.16 (both 32bit and x64 version) but the game crashed at same place both times (Either in audio settings or after the load game completes)
- After this, I tried replacing the dll files from CLEO zip with Silent's vorbis dll files (both). This time, cleo.log file was generated but the game didn't load any cleo files. The log files contained some crashes (as those files might not be compatible with cleo) and so, the game started with 0x000000 which I think means starts normally)

Last thing is to Install and use US 1.0 version but I dont know if there would be any fixes in that

If possible, kindly point me in correct direction ?

**Comment by hesoyamhh** [comment]
@x87 @JuniorDjjr please...... any help would be appreciated

**Comment by JuniorDjjr** [comment]
Use 1.0 US version and try https://www.mixmods.com.br/2021/06/crashinfo.html

Maybe the problem isn't related to CLEO, but your game.

Also, you said that the game crashes when changing the ratio station, and you said that you downloaded a repack. Prefer to download the vanilla. Bass.dll does nothing with the radio stations.

**Comment by hesoyamhh** [comment]
Thanks @JuniorDjjr for the input

> Use 1.0 US version and try https://www.mixmods.com.br/2021/06/crashinfo.html
> 
> Maybe the problem isn't related to CLEO, but your game.


The game runs fine normally and also with Silent's ASI Loader. The new Repack is nothing but v1.0.0.22 from Rockstar Launcher, patched and then compressed for easy installation. I was under impression that new version would have fixes and other patches which would help in playing the game with more ease... but I think it wont work.

Also, crashinfo is only for US 1.0 but will give it a try :)


> Also, you said that the game crashes when changing the ratio station, and you said that you downloaded a repack. Prefer to download the vanilla. Bass.dll does nothing with the radio stations.


Okay, As soon as cleo was installed, the game was crashing at radio setting or after game load, removing cleo made the game start normally and so, I thought bass.dll was the culprit.

**Comment by hesoyamhh** [comment]
@JuniorDjjr everything works fine with GTA:SA 1.0 US, Thanks!

Happy that I can play this game but sad that I was not able to make CLEO work with latest version.
