### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by TheArtemMaps** [cleolibrary/CLEO4#44]
hi there! can you please help me to fix the game crash after 5-10 minutres? heres the log
[cleo.log](https://github.com/cleolibrary/CLEO4/files/7237789/cleo.log)
:

**Comment by x87** [comment]
you have way too many active scripts. it's likely that some of them may conflict. try to identify the script causing the crash by disabling (removing from CLEO folder) scripts one by one.

**Comment by TheArtemMaps** [comment]
> you have way too many active scripts. it's likely that some of them may conflict. try to identify the script causing the crash by disabling (removing from CLEO folder) scripts one by one.

**Comment by TheArtemMaps** [comment]
> > you have way too many active scripts. it's likely that some of them may conflict. try to identify the script causing the crash by disabling (removing from CLEO folder) scripts one by one.

i will try it

**Comment by TheArtemMaps** [comment]
what is this mean? GTA:SA Crashed, Debug Info Follows:



GTA Info:



Error: Unknown



Assembly Info:



Exception At Address: 0x007F18CF

Exception Code: 0xc0000005 (EXCEPTION_ACCESS_VIOLATION)



Registers:

EAX: 0x00020000	EBX: 0x00000000

ECX: 0x00000178	EDX: 0x10D86990

ESI: 0x110DB940	EDI: 0x10D79EF0

EBP: 0x05C86080	ESP: 0x0028FD1C



Last Opcode: 0001 in thread 'cheats' (0x45B7474)

**Comment by x87** [comment]
try to install scrlog plugin and should be able to see what was the last script/opcode that crashed the game
https://github.com/JuniorDjjr/scrlog

**Comment by TheArtemMaps** [comment]
> try to install scrlog plugin and should be able to see what was the last script/opcode that crashed the game https://github.com/JuniorDjjr/scrlog

ok give me a sec

**Comment by TheArtemMaps** [comment]
> try to install scrlog plugin and should be able to see what was the last script/opcode that crashed the game https://github.com/JuniorDjjr/scrlog

log is empty

**Comment by TheArtemMaps** [comment]
[scrlog.log](https://github.com/cleolibrary/CLEO4/files/7253676/scrlog.log)
here's the log. so what script are calling a crash?

**Comment by x87** [comment]
I don't see any issues in this log. So it's likely that is not even a script that is causing a crash, but some other ASI plugin or mod.

**Comment by TheArtemMaps** [comment]
i have a cleo.asi modloader.asi discord-rpc.asi and SilentPatchSA.asi i need to remove them one by one right?

**Comment by x87** [comment]
Look up for your error 0x007F18CF in https://www.google.com/url?sa=t&source=web&rct=j&url=https://docs.google.com/document/d/1YLdADUoDvAoV3wFsPq25CXgm3IuCCoL6r3odkN14TlY/&ved=2ahUKEwiAzfXG5KTzAhVyFVkFHbwFBrsQFnoECBAQAQ&usg=AOvVaw0n57lUtC45X_RA5r5TzVXe


At this moment I don't think this is a CLEO issue
