### ISSUE TITLE
plane twitch

### ISSUE THREAD

**Issue by TheArtemMaps** [cleolibrary/CLEO4#46]
Hello everyone. I have a script that makes the plane fly to all 3 cities of the state. But the problem is they twitch. Or they ram into buildings. But I have to solve the jerking of the plane. can anyone help me please? here the script: ```
// This file was decompiled using SASCM.ini published on 2020-11-11
{$CLEO .cs}

0000: NOP 

:NONAME_2
wait 0 
077E: get_active_interior_to $ACTIVE_INTERIOR 
if or
   not $ACTIVE_INTERIOR == 0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere 877.9877 -28.3817 63.1953 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere 2025.451 997.5287 10.8203 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -694.6745 956.7463 12.2547 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -2025.717 157.9236 29.0391 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -2037.857 -2525.165 30.625 radius 60.0 60.0 60.0 
jf @NONAME_228 
jump @NONAME_2 
jump @NONAME_551 

:NONAME_228
4@ = 1374.069 
5@ = -1889.234 
6@ = 612.8045 
7@ = -1295.609 
if and
0154:   actor $PLAYER_ACTOR in_zone 'LA' 
00A3:   actor $PLAYER_ACTOR sphere 0 in_rectangle_cornerA 4@ 5@ cornerB 6@ 7@ 
jf @NONAME_338 
Model.Load(593)
038B: load_requested_models 
jump @NONAME_551 
jump @NONAME_551 

:NONAME_338
4@ = -2697.084 
5@ = 374.9268 
6@ = -2114.359 
7@ = 1189.876 
if and
0154:   actor $PLAYER_ACTOR in_zone 'SF' 
00A3:   actor $PLAYER_ACTOR sphere 0 in_rectangle_cornerA 4@ 5@ cornerB 6@ 7@ 
jf @NONAME_448 
Model.Load(593)
038B: load_requested_models 
jump @NONAME_551 
jump @NONAME_551 

:NONAME_448
4@ = 1574.103 
5@ = 2159.21 
6@ = 2486.055 
7@ = 1407.873 
if and
0154:   actor $PLAYER_ACTOR in_zone 'VE' 
00A3:   actor $PLAYER_ACTOR sphere 0 in_rectangle_cornerA 4@ 5@ cornerB 6@ 7@ 
jf @NONAME_2 
Model.Load(593)
038B: load_requested_models 
jump @NONAME_551 

:NONAME_551
wait 0 
if and
   Model.Available(593)
0208: 0@ = random_float_in_ranges 4@ 6@ 
0208: 1@ = random_float_in_ranges 5@ 7@ 
02CE: 2@ = ground_z_at 0@ 1@ 1000.0 
2@ += 100.0 
0208: 3@ = random_float_in_ranges 0.0 360.0 
Car.Create(8@, 593, 0@, 1@, 2@)
Car.Angle(8@) = 3@
Car.LockInCurrentPosition(8@, True)
Marker.CreateAboveCar(14@, 8@)
Object.Init(12@, 593, 0.0, 0.0, 0.0)
Object.Angle(12@) = 3@
0681: attach_object 12@ to_car 8@ with_offset 0.0 0.0 0.0 rotation 0.0 0.0 0.0 
Model.Destroy(593)
0560: create_random_actor_in_car 8@ handle_as 10@ 
Actor.SetImmunities(10@, True, True, True, True, True)
0209: 13@ = random_int_in_ranges 0 4 
if 
  13@ == 1 
jf @NONAME_882 
13@ = Audiostream.Load3D("CLEO\SOUND\VC_DODO1.WAV")
Audiostream.PerformAction(13@, AudioStreamState.Play)
Audiostream.Volume(13@) = 4.0
Audiostream.Loop(13@, 1)
Audiostream.LinkToCar(13@, 8@)
02D4: car 8@ turn_off_engine 
jump @NONAME_967 

:NONAME_882
if 
  13@ == 2 
jf @NONAME_967 
13@ = Audiostream.Load3D("CLEO\SOUND\VC_DODO2.WAV")
Audiostream.PerformAction(13@, AudioStreamState.Play)
Audiostream.Volume(13@) = 4.0
Audiostream.Loop(13@, 1)
Audiostream.LinkToCar(13@, 8@)
02D4: car 8@ turn_off_engine 

:NONAME_967
jump @NONAME_974 

:NONAME_974
wait 0 
0208: 3@ = random_float_in_ranges -0.1 0.1 
if or
  -0.05 > 3@ 
  3@ > 0.05 
jf @NONAME_974 
jump @NONAME_1109 

:NONAME_1031
wait 0 
0407: store_coords_to 0@ 1@ TIMERA from_car 8@ with_offset 0.0 0.5 0.0 
Car.PutAt(8@, 0@, 1@, 2@)
9@ = Car.Angle(8@)
005B: 9@ += 3@ // (float) 
Car.Angle(8@) = 9@
jump @NONAME_1109 

:NONAME_1109
wait 0 
if and
8495:   not car 8@ burning 
   not Car.Wrecked(8@)
jf @NONAME_1430 
if or
0202:   actor $PLAYER_ACTOR near_car 8@ radius 400.0 400.0 sphere 0 
00A3:   actor $PLAYER_ACTOR sphere 0 in_rectangle_cornerA 4@ 5@ cornerB 6@ 7@ 
jf @NONAME_1399 
077E: get_active_interior_to $ACTIVE_INTERIOR 
if or
   not $ACTIVE_INTERIOR == 0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere 877.9877 -28.3817 63.1953 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere 2025.451 997.5287 10.8203 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -694.6745 956.7463 12.2547 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -2025.717 157.9236 29.0391 radius 60.0 60.0 60.0 
00FE:   actor $PLAYER_ACTOR sphere 0 in_sphere -2037.857 -2525.165 30.625 radius 60.0 60.0 60.0 
jf @NONAME_1031 
jump @NONAME_1399 

:NONAME_1399
wait 0 
Audiostream.Release(13@)
Object.Destroy(12@)
Actor.RemoveReferences(10@)
Car.RemoveReferences(8@)
jump @NONAME_2 

:NONAME_1430
wait 0 
Car.LockInCurrentPosition(8@, False)
jump @NONAME_1448 

:NONAME_1448
wait 0 
11@ = Player.WantedLevel($PLAYER_CHAR)
if 
   not 11@ >= 2 
jf @NONAME_1399 
11@ += 1 
Player.WantedLevel($PLAYER_CHAR) = 11@
jump @NONAME_1448 

```

**Comment by x87** [comment]
Sorry, we are not doing mod support here. Only questions/requests related to CLEO library itself
