### ISSUE TITLE
GTA SA Crash after installing CLEO 4 with no mods

### ISSUE THREAD

**Issue by ScottsplaysSus** [cleolibrary/CLEO4#47]
Hey guys, GTA SA (V1.0, the original 1.0 version) crashes when I try to run a new game with CLEO 4(v4.4.0). At first, I thought the problem is caused by the mods, so I removed them. But GTA SA still crashes. To test that it is working without CLEO, I reinstalled the game and run it. It can run a new game and save the game. After installing CLEO 4, it crashes. I tried installing SilentPatch, AntiCrash v0.3.7, but it still didn't work. Please help, thanks.

**Comment by x87** [comment]
can you share cleo.log?

**Comment by ScottsplaysSus** [comment]
Here you go. 

[cleo.log](https://github.com/cleolibrary/CLEO4/files/7450283/cleo.log)

**Comment by ScottsplaysSus** [comment]
Here's the text inside the log file. 


01/11/2021 09:48:19.330 Log started.
01/11/2021 09:48:19.331 Unprotecting memory region '.text': 0x00001000 (size: 0x00456000)
01/11/2021 09:48:19.331 Unprotecting memory region '.rdata': 0x00458000 (size: 0x0004C000)
01/11/2021 09:48:19.331 Unprotecting memory region '.text': 0x008B1000 (size: 0x0064A000)
01/11/2021 09:48:19.331 Unloading plugins...
01/11/2021 09:48:19.331 Loading plugin cleo/FileSystemOperations.cleo
01/11/2021 09:48:19.334 Loading plugin cleo/IniFiles.cleo
01/11/2021 09:48:19.336 Loading plugin cleo/IntOperations.cleo
01/11/2021 09:48:19.337 Started on game of version: SA 1.0 us
01/11/2021 09:48:19.338 Injecting MenuStatusNotifier...
01/11/2021 09:48:19.338 Replacing call: 0x0057B9FD
01/11/2021 09:48:19.338 Injecting DmaFix...
01/11/2021 09:48:19.338 Replacing call: 0x0053E981
01/11/2021 09:48:19.338 Injecting TextManager...
01/11/2021 09:48:19.338 Injecting function at: 0x006A0050
01/11/2021 09:48:19.338 Injecting SoundSystem...
01/11/2021 09:48:19.338 Replacing call: 0x007487A8
01/11/2021 09:48:19.338 Injecting CustomOpcodeSystem...
01/11/2021 09:48:19.338 Injecting ScriptEngine...
01/11/2021 09:48:19.338 Replacing call: 0x0046A21B
01/11/2021 09:48:19.338 Replacing call: 0x0058D552
01/11/2021 09:48:19.338 Replacing call: 0x0058FCE4
01/11/2021 09:48:19.338 Replacing call: 0x0053BDD7
01/11/2021 09:48:19.338 Replacing call: 0x005BA340
01/11/2021 09:48:19.338 Replacing call: 0x005D4FD7
01/11/2021 09:48:19.338 Replacing call: 0x005D18F0
01/11/2021 09:48:19.338 Replacing call: 0x005D14D5
01/11/2021 09:48:19.338 Injecting function at: 0x004667DB
01/11/2021 09:48:19.666 Creating main window...
01/11/2021 09:48:19.670 Found sound device 0: No sound
01/11/2021 09:48:19.670 Found sound device 1 (default): Headphones (Realtek(R) Audio)
01/11/2021 09:48:19.670 Found sound device 2: Speakers (Realtek(R) Audio)
01/11/2021 09:48:19.670 On system found 3 devices, 3 enabled devices, assuming device to use: 1 (Headphones (Realtek(R) Audio))
01/11/2021 09:48:19.714 SoundSystem initialized
01/11/2021 09:48:19.723 Floating-point audio supported!
01/11/2021 09:48:19.727 Audio hardware acceleration disabled (no EAX)
01/11/2021 09:48:35.244 Closing SoundSystem...
01/11/2021 09:48:35.244 Freeing BASS library
01/11/2021 09:48:35.245 SoundSystem closed!
01/11/2021 09:48:35.245 Deleting fxts...
01/11/2021 09:48:35.245 Unloading scripts...
01/11/2021 09:48:35.245 Log finished.

**Comment by x87** [comment]
do you have any files in cleo\cleo_saves? if yes, can you remove them?
what is the error message when the game crashes?

**Comment by ScottsplaysSus** [comment]
The cleo_saves folder does not contain any files inside it. How to check the error message?

**Comment by ScottsplaysSus** [comment]
No, it crashes immediately after I click the "New game" button.

**Comment by x87** [comment]
if you delete cleo.asi from your game directory does the crash happen?

**Comment by ScottsplaysSus** [comment]
Unfortunately, it didn't help. I deleted the cleo.asi file, but it still crashes after I pressed the "New game" button.

**Comment by ScottsplaysSus** [comment]
Here is the directory for your reference. 


<img width="636" alt="GTA SA Directory" src="https://user-images.githubusercontent.com/91255736/139620675-33f17665-f0b4-4d50-9edc-2149f4dad839.png">

**Comment by x87** [comment]
If game still crashes after deleting cleo.asi, it can be something else that is incompatible with your gane version. It can be ASI loader or other mod. Alsobtry deleting gta_sa.set from user files directory

**Comment by ScottsplaysSus** [comment]
Thanks for the reply! Unfortunately, it still didn't work for me. I tried deleting the gta_sa.set file from `This PC/ Documents/GTA San Andreas User Files`, but it still didn't work. Also, I don't have any mods nor ASI Loader installed. Is it because I didn't install ASI Loader? 

Note that I'm running the game on Windows 10 with Compatibility Mode for Windows 7. I'm also running the game as an Administrator. 

My game version is GTA SA 1.0 US(you can refer to it in the cleo.log). 


I'm running Windows 10 Enterprise 21H1, with Intel i5-1035G1@1.00GHz, Nvidia GeForce MX330, and 12 GB of RAM on an Asus laptop(it is terrible ngl).

**Comment by x87** [comment]
you have ASI loader installed - it's vorbisFile.dll (2014) that replaces the original file (named as vorbisHooked.dll). You can try to delete vorbisFile.dll and rename vorbisHooked.dll to vorbisFile.dll to get vanilla experience, but I never heard of any issues with this loader.

Having GTA SA installed in `Program Files (x86)` could very well be the issue too especially on paranoid Win10 and UAC enabled.

Try the following:

1. Get clean, vanilla 1.0 version. No mods, patches whatsoever.
2. Install in a safe location outside of system directories.
3. Verify it's working. You should not need to run in admin mode.
4. If works, download CLEO4 archive from cleo.li and unpack to the game directory.
5. Verify it's working.

**Comment by x87** [comment]
I usually install GTA SA from Steam and run the game via gta_sa_compact.exe. Never had any issues.

**Comment by ScottsplaysSus** [comment]
Sorry for the late reply. It's midnight at my timezone. Anyway, I tried installing it outside the `C:/Program Files(x86)` directory, and it finally works! It even works with the mods now! Thank you so much, I really appreciate the help!
