### ISSUE TITLE
New CLEO codes crashing my game

### ISSUE THREAD

**Issue by Pledix** [cleolibrary/CLEO4#53]
I don't now why but new cleo codes crashing my game.
`0AC1: $test = load_audio_stream_with_3d_support "cleo\sounds\test.mp3"` (this code works perfectly)
`AudioStream3D.Load("cleo\sounds\test.mp3", $test)` (but this is crashing my game)

**Comment by x87** [comment]
if you just updated `classes.db` but did not update `SASCM.ini` then your parameters should be in the same order as in the opcode form. this should work
```
AudioStream3D.Load($test, "cleo\sounds\test.mp3")
```

alternatively you can open up SASCM.ini and change the opcode definition to

```
0AC1=2,load_3d_audio_stream %1d% store_to %2d%
```
then you can write
```
AudioStream3D.Load("cleo\sounds\test.mp3", $test)
0AC1: load_3d_audio_stream  "cleo\sounds\test.mp3" store_to $test
```

**Comment by Pledix** [comment]
I updated these files in Sanny Builder 3.8.0
![image](https://user-images.githubusercontent.com/22866860/152334970-c5decf5f-ee26-42f2-9154-6f417767091d.png)

Where can I find the current version of the SASCM.ini file?

**Comment by x87** [comment]
You can use SASCM.ini from SA SCR mode, it will be the closest shot.

New library's classes are still experimental and there is no official support in Sanny Builder yet. You work with them at your own risk. Refer to this ticket for information on the progress of adding the support in SB: https://github.com/sannybuilder/dev/issues/170

**Comment by Pledix** [comment]
Thanks for the feedback, keep up the good work!
