### ISSUE TITLE
0AAA should also work with game scripts

### ISSUE THREAD

**Issue by mfisto** [cleolibrary/CLEO4#56]
Ошибка Опкод не обрабытывает потоки мейна.

**Comment by x87** [comment]
0AAA should also work with game scripts

**Comment by x87** [comment]
CRunningScript has next and prev fields mixed up
https://github.com/cleolibrary/CLEO4/blob/master/source/CTheScripts.h#L44-L45
should be the other way around. it halts the iterator after the first script when we scan active scripts
