### ISSUE TITLE
Where can I see the documentation?

### ISSUE THREAD

**Issue by Martini002** [cleolibrary/CLEO4#57]
I'm trying to create a script, but would be helpful if I can check the documentation of this library, thank you

**Comment by x87** [comment]
you may want to start with https://gtamods.com/wiki/CLEO/Tutorial

**Comment by Martini002** [comment]
I would like to find the functions

**Comment by x87** [comment]
Define a "function"

**Comment by Martini002** [comment]
> Define a "function"

@Set_Virtual_Key

**Comment by x87** [comment]
I don't think we have a single place documenting SCM functions. At least I'm not aware of any

**Comment by Martini002** [comment]
I see, where do you access some of the functions?
