### ISSUE TITLE
AudioStream Stereo Audio Fix

### ISSUE THREAD

**Issue by CTXmaps** [cleolibrary/CLEO4#59]
I've figured out that Audio Stream is hardcoded as MONO only, due to flags definition mistake or something?
Here's the call of BASS_Init [( source/CSoundSystem.cpp ):](https://github.com/cleolibrary/CLEO4/blob/1871e6380c3bf2bfa068758b8c97dceb076b23ea/source/CSoundSystem.cpp#L101)
3rd param (flags) is (BASS_DEVICE_3D | BASS_DEVICE_DEFAULT) which is = 6
but if we look at the Bass docs we'll see that BASS_DEVICE_MONO definition is equal to BASS_DEVICE_DEFAULT
http://www.un4seen.com/doc/#bass/BASS_Init.html
So, "BASS_Init" function takes BASS_DEVICE_MONO in, which causes all audios to play MONO.
My quick dirty solution was to patch bit-flags from "6" to "4".
Just letting you know.

**Comment by CTXmaps** [comment]
@x87  Correct. But, all these years we had mono only sounds and it worked. I wouldn't recommend force this change for all users at this moment, need further testing to make sure there will be no problems with stereo sound.

I'm working on some GTA SA storyline, so I'll be testing it and I'll post here when I'll be mostly sure it won't cause any problems.

For anyone who want to try stereo sound, here's what you can do:

Open "cleo.asi" with any hex editor;
Go to "00010F4E", change "06" to "04";
Save.

You'll get audio quality increase due to stereo support, also audio panning support.

**Comment by x87** [comment]
closed via #61
