### ISSUE TITLE
Cleo 4.4 crashes on GTA SA v1.0 USA

### ISSUE THREAD

**Issue by Octavio1994** [cleolibrary/CLEO4#64]
I have GTA SA v1.0 USA with CLEO 4.0 and many mods installed on it. 

I can pass all the game's story without any issue, 

When I install cleo 4.4 or 4.4.1 the game just crashes when I shoot a pedestrian in the back, I don't get any error message and the game just crashes and throws me back to my desk

Currently using Windows 7

**Comment by Octavio1994** [comment]
In this video you can see the issue I have while playing

https://www.youtube.com/watch?v=XX6L5ggKViY

**Comment by x87** [comment]
Most likely it is a mod issue. Try to delete mods one by one to identify which one is causing a crash.

**Comment by Octavio1994** [comment]
> Most likely it is a mod issue. Try to delete mods one by one to identify which one is causing a crash.

It will take some time to do, but I really wonder why something that works fine with an old cleo version crashes when you install a more recent one

**Comment by x87** [comment]
Resolved in #65
