### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by TORREX18personal** [cleolibrary/CLEO4#66]
perdon si escribo esto en español pero no me gusta usar el traductor

Descargue cleo 4 otra vez por que me crasheaba el GTA, cuando lo descargue antes no me saltaba el antivirus, lo analizaba y no saltaban alarmas, pero lo descargo de nuevo
![imagen](https://user-images.githubusercontent.com/104810699/195976733-4235796a-3d86-4ee1-9818-0ad111d3de9d.png)
 y me tira esta alerta

**Comment by x87** [comment]
By nature CLEO runs in the game process and hooks/intercepts some function/sys calls. It might be considered by some antivirus programs as suspicious behavior. 

The source code of CLEO is open and you can inspect it and build your own version using Visual Studio.

If you still have doubts, just don't use CLEO.
