### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TORREX18personal** [cleolibrary/CLEO4#67]
otro problema es que salta un crasheo con otras versiones de cleo 4, (versiones que ya tenia antes)
y crashean, cleo 3 no me da errores, pero no puedo usarlo, ya que varios mods se han actualizado y no son compatibles con cleo 3

![imagen](https://user-images.githubusercontent.com/104810699/195977060-7b8f8979-5bf6-47cb-80f6-23020cb4031b.png)

**Comment by x87** [comment]
Most likely it is a mod issue. Try to delete mods one by one to identify which one is causing a crash.

**Comment by TORREX18personal** [comment]
I tried it in a clean gta, without any mods, it's a matter of putting cleo so that it crashes when starting a game (New Game)

**Comment by x87** [comment]
Make sure you have the version 1.0 (US) or gta_sa_compact

**Comment by TORREX18personal** [comment]
Does it have to do with it being 1.01? As a good Latin American that I am, I don't have a good PC, nor money to buy GTA, so I have it pirated

so I don't know if this version that I downloaded 1.01, (crackers almost always use the latest version) is the cause of the problem, yes, if it is the American version.

**Comment by x87** [comment]
#35

**Comment by TORREX18personal** [comment]
![imagen](https://user-images.githubusercontent.com/104810699/195998542-9b27479a-a274-4f70-9260-7578eabe37c9.png)

now it gives me this error, I already have 1.0, ASI and CLEO

**Comment by TORREX18personal** [comment]
ignore it, I was running the test version XD

**Comment by TORREX18personal** [comment]
![imagen](https://user-images.githubusercontent.com/104810699/195998704-ba8bf87e-6021-4224-82d7-ae03f6e1d446.png)
I already tried the corrected version with ASI, GTA 1.0 and CLEO, it still gives an error

**Comment by TORREX18personal** [comment]
It seems that this time it gives a different error

(without any mods)

**Comment by x87** [comment]
Does it work when you delete cleo.asi?
Show cleo.log file

**Comment by TORREX18personal** [comment]
yes, eliminating cleo does not give errors, here is the log

15/10/2022 11:25:26.649 Log started.
15/10/2022 11:25:26.650 Unprotecting memory region '.text': 0x00001000 (size: 0x00457000)
15/10/2022 11:25:26.650 Unprotecting memory region '.rdata': 0x00459000 (size: 0x0004C000)
15/10/2022 11:25:26.650 Unprotecting memory region '.text': 0x008B3000 (size: 0x00528000)
15/10/2022 11:25:26.661 Unloading plugins...
15/10/2022 11:25:26.661 Loading plugin cleo/FileSystemOperations.cleo
15/10/2022 11:25:26.724 Loading plugin cleo/IniFiles.cleo
15/10/2022 11:25:26.767 Loading plugin cleo/IntOperations.cleo
15/10/2022 11:25:26.772 Started on game of version: SA 1.01 eu
15/10/2022 11:25:26.773 Injecting MenuStatusNotifier...
15/10/2022 11:25:26.773 Replacing call: 0x0057BF71
15/10/2022 11:25:26.773 Injecting DmaFix...
15/10/2022 11:25:26.773 Replacing call: 0x0053EE21
15/10/2022 11:25:26.773 Injecting TextManager...
15/10/2022 11:25:26.773 Injecting function at: 0x006A0870
15/10/2022 11:25:26.773 Injecting SoundSystem...
15/10/2022 11:25:26.773 Replacing call: 0x0074907C
15/10/2022 11:25:26.773 Injecting CustomOpcodeSystem...
15/10/2022 11:25:26.774 Injecting ScriptEngine...
15/10/2022 11:25:26.774 Replacing call: 0x0046AE9B
15/10/2022 11:25:26.774 Replacing call: 0x0058DD22
15/10/2022 11:25:26.774 Replacing call: 0x005904B4
15/10/2022 11:25:26.774 Replacing call: 0x005D57B7
15/10/2022 11:25:26.774 Injecting function at: 0x005DEEA0
15/10/2022 11:25:26.774 Replacing call: 0x005D20D0
15/10/2022 11:25:26.774 Replacing call: 0x005D157C
15/10/2022 11:25:26.774 Injecting function at: 0x0046685B
15/10/2022 11:25:27.953 Creating main window...
15/10/2022 11:25:27.982 Found sound device 0: No sound
15/10/2022 11:25:27.982 Found sound device 1 (default): Altavoces (VIA High Definition Audio)
15/10/2022 11:25:27.982 On system found 2 devices, 2 enabled devices, assuming device to use: 1 (Altavoces (VIA High Definition Audio))
15/10/2022 11:25:28.020 SoundSystem initialized
15/10/2022 11:25:28.021 Floating-point audio supported!
15/10/2022 11:25:28.022 Audio hardware acceleration disabled (no EAX)
15/10/2022 11:27:13.799 Closing SoundSystem...
15/10/2022 11:27:13.800 Freeing BASS library
15/10/2022 11:27:13.800 SoundSystem closed!
15/10/2022 11:27:13.800 Deleting fxts...
15/10/2022 11:27:13.800 Unloading scripts...
15/10/2022 11:27:13.800 Log finished.

**Comment by TORREX18personal** [comment]
but i can't run mods

**Comment by x87** [comment]
> 15/10/2022 11:25:26.772 Started on game of version: SA 1.01 eu

**Comment by TORREX18personal** [comment]
bruh

**Comment by TORREX18personal** [comment]
ok, time to retry the process

(my level of english is a shit)

**Comment by TORREX18personal** [comment]
solved, thanks
