### ISSUE TITLE
When you rotate the mouse around the character, the sound goes to the right speaker, then to the left.

### ISSUE THREAD

**Issue by imLEGR** [cleolibrary/CLEO4#70]
When you rotate the mouse around the character, the sound goes to the right speaker, then to the left. The problem is the bass.dll file. I found the same bass.dll, but a little bigger, and with it the sound works fine. I'm playing on Arch Linux. Please fix the bass.dll.

Because when I turn the mouse around my character the sound goes to one column and when I switch between menu items the sound is still in one column.

I attach the bass.dll from ZMenuSA_v22.12.16.1 below.

[bass.tar.gz](https://github.com/cleolibrary/CLEO4/files/10272116/bass.tar.gz)

**Comment by Tortillas-IT** [comment]
i had the same issue, now this is fixed... still there are audio degredation and minor crackling
