### ISSUE TITLE
Doesn't work in GTA SA official version from Rockstar

### ISSUE THREAD

**Issue by Jonikster** [cleolibrary/CLEO4#74]
Bought the game here:
https://store.rockstargames.com/game/buy-grand-theft-auto-the-trilogy
This includes the 2005 release, not the definitive edition.
So and CLEO doesn't work with that...

**Comment by x87** [comment]
Find and download gta-sa exe version 1.0. Most mods/plugins support 1.0 anyway

**Comment by Jonikster** [comment]
> Find and download gta-sa exe version 1.0. Most mods/plugins support 1.0 anyway

I don't think it will be legal. I live in the UK and piracy is a criminal offense here

**Comment by x87** [comment]
It is a piracy, as you own a copy of the game (not a legal advice though). You can either search for downgrading software that transform your exe into v1.0, or enjoy vanilla experience.

**Comment by x87** [comment]
https://gtaforums.com/topic/927016-san-andreas-downgrader/
