### ISSUE TITLE
CLEO bass.dll breaks GTA SA's Audio System

### ISSUE THREAD

**Issue by ko32190** [cleolibrary/CLEO4#77]
I noticed that when Cleo is installed, San Andreas' audio is messed up. For example, the audio field isn't correctly linked to the camera, causing all audio except for cutscene audio to rotate out of sync with the camera. Another issue is that some of the audio, like cars, becomes mono and won't play in stereo or surround. The last issue is BASS. DLL breaks EAX hardware-accelerated audio support, preventing it from working at all. This is especially noticeable with headphones.
[cleo.log](https://github.com/cleolibrary/CLEO4/files/11775762/cleo.log)

**Comment by x87** [comment]
Can you try bass.dll from #70 and report back if it fixes the problem?

**Comment by ko32190** [comment]
I can confirm, https://github.com/cleolibrary/CLEO4/issues/70 fixes the issue.
