### ISSUE TITLE
34@

### ISSUE THREAD

**Issue by Second2952** [cleolibrary/CLEO4#88]
Using the local variable 34@ will cause most random cleo scripts to be unregistered during the game

**Comment by MiranDMC** [comment]
Are we talking about cs scripts? You know that variable @34 is not valid, and by using it you just overwrite other data in running script structure? It this case 34@ accesses ```bool m_bIsActive;```, which explains the effects you are experiencing.
https://github.com/DK22Pac/plugin-sdk/blob/b0ebc6e4f44c2d5f768b36c6a7a2a688e7e2b9d3/plugin_sa/game_sa/CRunningScript.h#L89C6-L89C33
