### ISSUE TITLE
SCM function should keep its own gosub stack

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO4#96]
```
{$CLEO .cs}

gosub @gosub

0109: player $PLAYER_CHAR money += 444
terminate_this_custom_script

:gosub
cleo_call @cleo_call 0

:cleo_call
return
```

Expectation: crash on return command, as gosub stack is empty inside the function. 
Actual result: execution continues to 0109 and 0A93

**Comment by x87** [comment]
We should save current stack and stack pointer on calling a function and restore after cleo_return.

https://github.com/cleolibrary/CLEO4/blob/master/source/CTheScripts.h#L79-L80

**Comment by MiranDMC** [comment]
[https://github.com/cleolibrary/CLEO4/pull/97](url)
